In [1]:
#We can create numpy arrays with more than one dimension
#This section will focus only on 2D arrays, but you can use numpy to build arrays of much higher dimensions


#In this video we will cover the basics and array creation in 2D
#indexing and slicing in 2D, and basic operations in 2D

#3D
#The list contains three nested lists each of equal size
import numpy as np
print('\n LIST:')
list3d=[[23,4,5,6],[11,4, 7, 3],[34, 74, 4,9]]
print (list3d)
numlist=np.array(list3d)
print('\nNumpy 3D lists:\n', numlist)



 LIST:
[[23, 4, 5, 6], [11, 4, 7, 3], [34, 74, 4, 9]]

Numpy 3D lists:
 [[23  4  5  6]
 [11  4  7  3]
 [34 74  4  9]]


In [2]:
#Rectangular array
# It is helpful to visualize the numpy array as a rectangular array; 
# Each nested list corresponds to a different row of the matrix
# We can use the attribute "ndim" to obtain 
#the number of axes or dimensions referred to as the rank

#We can use the attribute "ndim" to obtain the number of "axes or dimensions" referred to as the rank
print(numlist.ndim)

#As with the 1d array, the attribute "shape" returns a tuple
#It’s helpful to use the rectangular representation as well
print(numlist.shape)
#The first element in the tuple corresponds to the number of nested lists contained in
#the original list or the number of rows in the rectangular representation, in this case 3
#The second element corresponds to the size of each of the nested lists
# or the number of columns in the rectangular array 0

#Size
# can also use the attribute size to get the size of the array
print(numlist.size)

# We can use rectangular brackets to access the different elements of the array

Z=np.array([[2,4], [24,5], [21,98]])
print('\nAccess to the 3D arrays by rectangular brackets:\n',Z)

Z=[[Z[0][0],Z[0][1]],[Z[1][0],Z[1][1]],[Z[2][0],Z[2][1]]]

# Using the rectangular representation, the
# first index corresponds to the row index
print('\n Numpy 3D array:\n',Z)
Z=np.array([[2,4], [24,5], [21,98]])
print(Z)

print('\nAccess to the 3D arrays  a single bracket:\n',Z)
# We can also use a single bracket to access the elements as follows
Z=[[Z[0,0],Z[0,1]],[Z[1,0],Z[1,1]],[Z[2,0],Z[2,1]]]


2
(3, 4)
12

Access to the 3D arrays by rectangular brackets:
 [[ 2  4]
 [24  5]
 [21 98]]

 Numpy 3D array:
 [[2, 4], [24, 5], [21, 98]]
[[ 2  4]
 [24  5]
 [21 98]]

Access to the 3D arrays  a single bracket:
 [[ 2  4]
 [24  5]
 [21 98]]


In [3]:
#slicing
#We can also use slicing in numpy arrays
#The first index corresponds to the first row
#The second index accesses the first two columns
import numpy as np
print('\n LIST:')
list3d=[[23,4,5,6],[11,4, 7, 3],[34, 74, 4,9]]
print (list3d)
numlist=np.array(list3d)
print('\nNumpy 3D lists:\n', numlist)

print('\n #slicing [0,0:3]:')
print(numlist[0,0:3])

print('\n #slicing [0:2, 0:3]:')
print(numlist[0:2,0:3])

print('\n #slicing [0:2, 2]:')
print(numlist[0:2,2])

print('\n #slicing [0:3, 0:2]:')
print(numlist[0:3,0:2])


 LIST:
[[23, 4, 5, 6], [11, 4, 7, 3], [34, 74, 4, 9]]

Numpy 3D lists:
 [[23  4  5  6]
 [11  4  7  3]
 [34 74  4  9]]

 #slicing [0,0:3]:
[23  4  5]

 #slicing [0:2, 0:3]:
[[23  4  5]
 [11  4  7]]

 #slicing [0:2, 2]:
[5 7]

 #slicing [0:3, 0:2]:
[[23  4]
 [11  4]
 [34 74]]


In [4]:
#Adding
#We can also add arrays; the process is identical to matrix addition
import numpy as np

list3d=np.array([[23,4,5,6],[11,4, 7, 3]])
print ('\n Matrix A:\n',list3d)

list3db=np.array([[-2, -5, 4, 9.6],[34, 74, 4,9]])
print ('\n Matrix B:\n',list3db)

result=list3d+list3db
print('\n Matrix A+ Matrix B:\n', result)



 Matrix A:
 [[23  4  5  6]
 [11  4  7  3]]

 Matrix B:
 [[-2.  -5.   4.   9.6]
 [34.  74.   4.   9. ]]

 Matrix A+ Matrix B:
 [[21.  -1.   9.  15.6]
 [45.  78.  11.  12. ]]


In [5]:
#Python
#Numpy
#Multiplying 
#Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler

import numpy as np
#Consider the matrix list2, if we multiply the matrix by the scaler 3
#we simply multiply every element in the matrix by 3
#The result is a new matrix of the same size
list2=np.array([[5,7,8],[2,4,6],[2,5,7],[11, 4, 6]])
print ('\n numpy array (list2):\n',list2)

Result=3* list2;
print ('\n Multiplying a numpy array (list2) by a scaler (3)>>> Result=3*list2:\n',Result)


Result=2* list2;
print ('\n Multiplying a numpy array (list2) by a scaler (2)>>> Result=2*list2:\n',Result)

Result=13.567* list2;
print ('\n Multiplying a numpy array (list2) by a scaler (13.567)>>> Result=13.567*list2:\n',Result)



list3=np.array([[2.4, 6.8],[9.3, 4.6],[2.9, 8.6]])
Result=1000.05* list3;
print ('\n Multiplying a numpy array (list3) by a scaler (1000)>>> Result=1000*list2:\n',Result)



 numpy array (list2):
 [[ 5  7  8]
 [ 2  4  6]
 [ 2  5  7]
 [11  4  6]]

 Multiplying a numpy array (list2) by a scaler (3)>>> Result=3*list2:
 [[15 21 24]
 [ 6 12 18]
 [ 6 15 21]
 [33 12 18]]

 Multiplying a numpy array (list2) by a scaler (2)>>> Result=2*list2:
 [[10 14 16]
 [ 4  8 12]
 [ 4 10 14]
 [22  8 12]]

 Multiplying a numpy array (list2) by a scaler (13.567)>>> Result=13.567*list2:
 [[ 67.835  94.969 108.536]
 [ 27.134  54.268  81.402]
 [ 27.134  67.835  94.969]
 [149.237  54.268  81.402]]

 Multiplying a numpy array (list3) by a scaler (1000)>>> Result=1000*list2:
 [[2400.12  6800.34 ]
 [9300.465 4600.23 ]
 [2900.145 8600.43 ]]


In [6]:
#Python Numpy
#Hadamard product
#Multiplication of two arrays corresponds to an element-wise product or Hadamard product

import numpy as bm
arryNm1=bm.array([[2,4], [62,4], [3,6]])
arryNm2=bm.array([[3,5], [26,2], [7,8]])
print('\n Print arrayNm1: \n', arryNm1)
print('\n print arrayNm2: \n', arryNm2)
#The result is a new matrix that is the same size as matrix Y or X
#Each element in this new matrix is the product of the corresponding elements in X and Y
Result=arryNm1*arryNm2
print("\nHadamard product Resulet=arrayNm1*arrayNm1:\n", Result)

#Ex2
ArryNm1=bm.array([[2,4], [3,6]])
ArryNm2=bm.array([[3,5], [7,8]])
print('\n Print aArrayNm1: \n', ArryNm1)
print('\n print ArrayNm2: \n', ArryNm2)
#The result is a new matrix that is the same size as matrix Y or X
#Each element in this new matrix is the product of the corresponding elements in X and Y
Result=ArryNm1*ArryNm2
print("\n Hadamard product Resulet=ArrayNm1*ArrayNm1:\n", Result)


 Print arrayNm1: 
 [[ 2  4]
 [62  4]
 [ 3  6]]

 print arrayNm2: 
 [[ 3  5]
 [26  2]
 [ 7  8]]

Hadamard product Resulet=arrayNm1*arrayNm1:
 [[   6   20]
 [1612    8]
 [  21   48]]

 Print aArrayNm1: 
 [[2 4]
 [3 6]]

 print ArrayNm2: 
 [[3 5]
 [7 8]]

 Hadamard product Resulet=ArrayNm1*ArrayNm1:
 [[ 6 20]
 [21 48]]


In [7]:
#Python
#Numpy
#The dot product
#We can also perform matrix multiplication with numpy arrays
#Matrix multiplication is a little more complex
#but let's provide a basic overview

import numpy as bm
arryNm1=bm.array([[2,4], [6.2,4], [3,6]])
arryNm2=bm.array([[3, 5, 9], [7.4, 7.8, 2.8]])
print('\n Print arrayNm1: \n', arryNm1)
print('\n print arrayNm2: \n', arryNm2)
#The result is a new matrix that is the same size as matrix Y or X
#Each element in this new matrix is the product of the corresponding elements in X and Y

# we must make sure that the number of columns in matrix "arrayNm1"in this case 3,
# is equal to the number of rows in matrix "arrayNm1", in this case 3

Result=np.dot(arryNm1,arryNm2)
print("\n Dot product 'np.dot' Resulet=arrayNm1.arrayNm2:\n", Result)

Result=np.dot(arryNm2,arryNm1)
print("\n Dot product 'np.dot' Resulet=arrayNm2.arrayNm1:\n", Result)


arryNm2=bm.array([[3, 5], [7.4, 7.8], [3.7, 8.6]])
arryNm1=bm.array([[2, 4, 5], [6.2, 4, 5.5]])
print('\n Print arrayNm1: \n', arryNm1)
print('\n print arrayNm2: \n', arryNm2)
#The result is a new matrix that is the same size as matrix Y or X
#Each element in this new matrix is the product of the corresponding elements in X and Y

# we must make sure that the number of columns in matrix "arrayNm1"in this case 3,
# is equal to the number of rows in matrix "arrayNm1", in this case 3

Result=np.dot(arryNm1,arryNm2)
print("\n Dot product 'np.dot' Resulet=arrayNm1.arrayNm2:\n", Result)

Result=np.dot(arryNm2,arryNm1)
print("\n Dot product 'np.dot' Resulet=arrayNm2.arrayNm1:\n", Result)





 Print arrayNm1: 
 [[2.  4. ]
 [6.2 4. ]
 [3.  6. ]]

 print arrayNm2: 
 [[3.  5.  9. ]
 [7.4 7.8 2.8]]

 Dot product 'np.dot' Resulet=arrayNm1.arrayNm2:
 [[35.6 41.2 29.2]
 [48.2 62.2 67. ]
 [53.4 61.8 43.8]]

 Dot product 'np.dot' Resulet=arrayNm2.arrayNm1:
 [[64.   86.  ]
 [71.56 77.6 ]]

 Print arrayNm1: 
 [[2.  4.  5. ]
 [6.2 4.  5.5]]

 print arrayNm2: 
 [[3.  5. ]
 [7.4 7.8]
 [3.7 8.6]]

 Dot product 'np.dot' Resulet=arrayNm1.arrayNm2:
 [[ 54.1   84.2 ]
 [ 68.55 109.5 ]]

 Dot product 'np.dot' Resulet=arrayNm2.arrayNm1:
 [[37.   32.   42.5 ]
 [63.16 60.8  79.9 ]
 [60.72 49.2  65.8 ]]
